In [6]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)
    print("syn0:")
    print(syn0)

print("Output After Training:")
print(l1)


syn0:
[[ 0.12025406]
 [ 0.50456196]
 [-0.85063774]]
syn0:
[[ 0.40563039]
 [ 0.54131537]
 [-0.72857311]]
syn0:
[[ 0.65701265]
 [ 0.53906065]
 [-0.66099969]]
syn0:
[[ 0.86828909]
 [ 0.50813544]
 [-0.64314383]]
syn0:
[[ 1.04900401]
 [ 0.46321233]
 [-0.65628104]]
syn0:
[[ 1.20838473]
 [ 0.41369083]
 [-0.68564552]]
syn0:
[[ 1.35233482]
 [ 0.36453375]
 [-0.7224582 ]]
syn0:
[[ 1.48437153]
 [ 0.31812411]
 [-0.76197545]]
syn0:
[[ 1.60664714]
 [ 0.27543379]
 [-0.80178627]]
syn0:
[[ 1.72057624]
 [ 0.23669265]
 [-0.84074522]]
syn0:
[[ 1.82717442]
 [ 0.20176514]
 [-0.87836247]]
syn0:
[[ 1.92723187]
 [ 0.17035575]
 [-0.91447348]]
syn0:
[[ 2.02140044]
 [ 0.14211607]
 [-0.94906762]]
syn0:
[[ 2.11023778]
 [ 0.11669744]
 [-0.98220216]]
syn0:
[[ 2.19423069]
 [ 0.09377462]
 [-1.01396057]]
syn0:
[[ 2.27380877]
 [ 0.07305471]
 [-1.04443286]]
syn0:
[[ 2.34935331]
 [ 0.05427874]
 [-1.07370691]]
syn0:
[[ 2.42120381]
 [ 0.03722   ]
 [-1.10186489]]
syn0:
[[ 2.48966335]
 [ 0.02168097]
 [-1.1289822 ]]
syn0:
[[ 2.5